name: facesegmentation  

channels:
  - defaults
  - conda-forge
  - pytorch  

dependencies:
  - python=3.10
  - pip
  - numpy
  - opencv
  - pillow
  - pip:
      - torch
      - torchvision
      - gradio
      - mediapipe
